module.exports = {
  reactStrictMode: true,
  env: {
    REACT_APP_GITHUB_CLIENT_ID: process.env.REACT_APP_GITHUB_CLIENT_ID,
    REACT_APP_GITHUB_CLIENT_SECRET: process.env.REACT_APP_GITHUB_CLIENT_SECRET,
    REACT_APP_KV_GITHUB_CLIENT_ID: process.env.REACT_APP_KV_GITHUB_CLIENT_ID,
    REACT_APP_KV_GITHUB_CLIENT_SECRET: process.env.REACT_APP_KV_GITHUB_CLIENT_SECRET,
    ETH_RPC_URL: process.env.ETH_RPC_URL,
  }
};
