require('dotenv').config();


const REACT_APP_GITHUB_CLIENT_ID = process.env.REACT_APP_GITHUB_CLIENT_ID;
const REACT_APP_GITHUB_CLIENT_SECRET = process.env.REACT_APP_GITHUB_CLIENT_SECRET;

const REACT_APP_KV_GITHUB_CLIENT_ID = process.env.REACT_APP_KV_GITHUB_CLIENT_ID;
const REACT_APP_KV_GITHUB_CLIENT_SECRET = process.env.REACT_APP_KV_GITHUB_CLIENT_SECRET;

const SERVER_PRIVATE_KEY = process.env.SERVER_PRIVATE_KEY;

const SERVER_PUBLIC_KEY = process.env.SERVER_PUBLIC_KEY;

const SERVER_AVATAR = process.env.SERVER_AVATAR;
