export const REACT_APP_GITHUB_CLIENT_ID = process.env.REACT_APP_GITHUB_CLIENT_ID;
export const REACT_APP_GITHUB_CLIENT_SECRET = process.env.REACT_APP_GITHUB_CLIENT_SECRET;

export const REACT_APP_KV_GITHUB_CLIENT_ID = process.env.REACT_APP_KV_GITHUB_CLIENT_ID;
export const REACT_APP_KV_GITHUB_CLIENT_SECRET = process.env.REACT_APP_KV_GITHUB_CLIENT_SECRET;

export const SERVER_PRIVATE_KEY = process.env.SERVER_PRIVATE_KEY;

export const ETH_RPC_URL = process.env.ETH_RPC_URL;

export const SERVER_PUBLIC_KEY = process.env.SERVER_PUBLIC_KEY;

export const SERVER_AVATAR = process.env.SERVER_AVATAR;
