name: CI-CD

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: pjhnocegood-deploy
  CODE_DEPLOY_APPLICATION_NAME: pjhnocegood-code-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: pjhnocegood-server

jobs:
  job_compute_diff:
    name: Compute file diff
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current commit (${{ github.sha }})
      uses: actions/checkout@v3
    - name: Compute diff
      uses: dorny/paths-filter@v2
      id: compute_diff
      with:
        filters: |
          files:
            - 'packages/A/**'
    outputs:
      files: ${{ steps.compute_diff.outputs.files }}
  build:
    runs-on: ubuntu-latest
  
    steps:
        - name: Deploy if Compute Diff is True
          if: ${{ needs.job_compute_diff.outputs.files != 'true' }}
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 20.9
        # - name: Change Working Directory
        #   run: cd /home/runner/work/discovey/discovey/backend
        #   working-directory: /home/runner/work/discovey/discovey/backend
        - name: Install Dependencies backend
          run: npm install
          working-directory: /home/runner/work/discovey/discovey/backend
        - name: Install Dependencies frontend
          run: npm install
          working-directory: /home/runner/work/discovey/discovey/frontend   
        - name: Build
          run: npm run build
          working-directory: /home/runner/work/discovey/discovey/frontend
        - name: Export
          run: npm run export
          working-directory: /home/runner/work/discovey/discovey/frontend  


        # [3]
        - name: Make zip file
          run: zip -r ./$GITHUB_SHA.zip .
          shell: bash

          # [4]
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
            aws-region: ${{ secrets.AWS_REGION }} 

          # [5]
        - name: Upload to S3
          run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

          # [6]
        - name: Code Deploy
          run: | 
            aws deploy create-deployment \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
